
// Common packages
const functions = require('firebase-functions');
const { Octokit } = require("@octokit/rest");
const octokit = new Octokit({
  auth: functions.config().github.token,
});
const bodyParser = require('body-parser');
const express = require('express');
const cors = require('cors');

/**
 * Submit an issue using Github's API
 *
 * All params are referenced from req.body
 * @param {string} title - Title for the issue
 * @param {string} body - Either the stack trace and props when the error occurred or input from the user
 * @param {bool} autoGenerated - True if sent automatically when error occurs in app
 * @param {bool} bug
 * @return {Object} {type, [data, error]}
 */
var submitIssue = express();

submitIssue.use(bodyParser.json()) // for parsing application/json
submitIssue.use(bodyParser.urlencoded({ extended: true })) // for parsing application/x-www-form-urlencoded

// Automatically allow cross-origin requests
submitIssue.use(cors({ origin: true }));

submitIssue.post('*', async (req, res) => {
  const title = req.body.title;
  const body = req.body.body;
  const bug = req.body.bug;
  const autoGenerated = req.body.autoGenerated;
  // Assign labels to issue
  var labels = [];
  if (autoGenerated) labels.push("auto-generated-bug")
  else {
    if (bug) labels.push("bug");
    else labels.push("feature");
  }
  
  var unique = true;
  var success = await octokit.issues.listForRepo({
    owner: "jbuxofplenty",
    repo: "atlas",
  })
  .then(({ data }) => {
    for(i in data){
      if(data[i].title == title) {
        unique = false;
      }
    }
    return true;
  })
  .catch(function(error) {
    res.send({ type: 'apiFailure', error: error.message });
    return false;
  });
  if(!success) return;
  if(!autoGenerated || unique) {
    octokit.issues.create({
      owner: "jbuxofplenty",
      repo: "atlas",
      title,
      body,
      labels
    })
    .then(({ data }) => {
      res.send({ type: 'success', data })
    })
    .catch(function(error) {
      res.send({ type: 'apiFailure', error: error.message })
    });
  }
  else {
    res.send({ type: 'success', data: 'Issue not created due to a similar issue existing in the database at this time.' });
  }
});

module.exports = {
    submitIssue,
};
