export const cryptoCurrencies = [
  { value: 'COINBASE:BTC-USD', label: 'Bitcoin (BTC)', color: '#00B8D9' },
  { value: 'COINBASE:ETH-USD', label: 'Ethereum (ETH)', color: '#0052CC' },
  { value: 'COINBASE:ALGO-USD', label: 'Algorand (ALGO)', color: '#5243AA' },
  { value: 'COINBASE:XTZ-USD', label: 'Tezos (XTZ)', color: '#616802' },
  { value: 'COINBASE:ATOM-USD', label: 'Atom (ATOM)', color: '#FF8B00' },
  { value: 'COINBASE:NMR-USD', label: 'Numerai (NMR)', color: '#FFC400' },
  { value: 'COINBASE:MKR-USD', label: 'Maker (MKR)', color: '#36B37E' },
  { value: 'COINBASE:EOS-USD', label: 'EOSIO (EOS)', color: '#00875A' },
  { value: 'COINBASE:XRP-USD', label: 'Ripple (XRP)', color: '#253858' },
  { value: 'COINBASE:LTC-USD', label: 'Litecoin (LTC)', color: '#666666' },
  { value: 'COINBASE:BCH-USD', label: 'Bitcoin Cash (BCH)', color: '#c15294' },
  { value: 'COINBASE:LINK-USD', label: 'Chainlink (LINK)', color: '#f12fa9' },
  { value: 'COINBASE:BAND-USD', label: 'Band (BAND)', color: '#54d311' },
  { value: 'COINBASE:ZRX-USD', label: 'Ox (ZRX)', color: '#c9612b' },
  { value: 'COINBASE:OXT-USD', label: 'Orchid (OXT)', color: '#ff8766' },
  { value: 'COINBASE:CVC-USDC', label: 'Civic (CVC)', color: '#ea26b0' },
  { value: 'COINBASE:ZEC-USDC', label: 'Zcash (ZEC)', color: '#27bef0' },
  { value: 'COINBASE:REP-USD', label: 'Augur (REP)', color: '#6d951f' },
  { value: 'COINBASE:OMG-USD', label: 'OMG Network (OMG)', color: '#e92dcd' },
  { value: 'COINBASE:UNI-USD', label: 'Uniswap (UNI)', color: '#df7e40' },
  { value: 'BINANCE:BCHSVTUSD', label: 'Bitcoin SV (BSV)', color: '#2E6802' },
];