import { isDev, apiBaseUrl } from 'helpers';

export async function submitIssue(title, body, label, autoGenerated) {
  if(!isDev() || !autoGenerated) {
    var success = await fetch(apiBaseUrl() + 'github/submitIssue/', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title,
        body,
        label,
        autoGenerated
      })
    })
    .then((response) => response.json())
    .then((responseJson) => {
      if(responseJson.type === "success") {
        console.log("Successfully packaged and sent bug to development team!")
        return true;
      }
      else {
        console.log("Error in response from github when sending bug to development team!")
        return false;
      }
    })
    .catch((error) => {
      console.log("Error in request when trying to send bug to development team!")
      console.log(error)
      return false;
    });
    return success;
  }
  
}