export const keys = {
  "3MonthAverageTradingVolume": ["Average Trading Volume", "3 Month"],
  "5DayPriceReturnDaily": ["Price Return Daily", "5 Day"],
  "10DayAverageTradingVolume": ["Average Trading Volume", "10 Day"],
  "13WeekPriceReturnDaily": ["Price Return Daily", "13 Week"],
  "26WeekPriceReturnDaily": ["Price Return Daily", "26 Week"],
  "52WeekHigh": ["52 Week", "High"],
  "52WeekHighDate": ["52 Week", "High Date"],
  "52WeekLow": ["52 Week", "Low"],
  "52WeekLowDate": ["52 Week", "Low Date"],
  "52WeekPriceReturnDaily": ["Price Return Daily", "52 Week"],
  "assetTurnoverAnnual": ["Asset Turnover", "Annual"],
  "assetTurnoverTTM": ["Asset Turnover", "TTM"],
  "bookValuePerShareAnnual": ["Book Value Per Share", "Annual"],
  "bookValuePerShareQuarterly": ["Book Value Per Share", "Quarterly"],
  "bookValueShareGrowth5Y": ["Book Value Share Growth", "5 Year"],
  "capitalSpendingGrowth5Y": ["Capital Spending Growth", "5 Year"],
  "cashFlowPerShareAnnual": ["Cash Flow Per Share", "Annual"],
  "cashFlowPerShareTTM": ["Cash Flow Per Share", "TTM"],
  "cashPerSharePerShareAnnual": ["Cash Per Share Per Share", "Annual"],
  "cashPerSharePerShareQuarterly": ["Cash Per Share Per Share", "Quarterly"],
  "currentDividendYieldTTM": ["Current Dividend Yield", "TTM"],
  "currentEv/freeCashFlowAnnual": ["Current EV/ Free Cash Flow", "Annual"],
  "currentEv/freeCashFlowTTM": ["Current EV/ Free Cash Flow", "TTM"],
  "currentRatioAnnual": ["Current Ratio", "Annual"],
  "currentRatioQuarterly": ["Current Ratio", "Quarterly"],
  "dividendGrowthRate5Y": ["Dividend Growth Rate", "5 Year"],
  "dividendPerShare5Y": ["Dividend Per Share", "5 Year"],
  "dividendPerShareAnnual": ["Dividend Per Share", "Annual"],
  "dividendYield5Y": ["Dividend Yield", "5 Year"],
  "dividendYieldIndicatedAnnual": ["Dividend Yield Indicated", "Annual"],
  "dividendsPerShareTTM": ["Dividends Per Share", "TTM"],
  "ebitdPerShareTTM": ["Ebitd Per Share", "TTM"],
  "ebitdaCagr5Y": ["EBITDA CAGR", "5 Year"],
  "ebitdaInterimCagr5Y": ["EBITDA Interim CAGR", "5 Year"],
  "epsBasicExclExtraItemsAnnual": ["EPS Basic (excludes extra)", "Annual"],
  "epsBasicExclExtraItemsTTM": ["EPS Basic (excludes extra)", "TTM"],
  "epsExclExtraItemsAnnual": ["EPS (excludes extra)", "Annual"],
  "epsExclExtraItemsTTM": ["EPS (excludes extra)", "TTM"],
  "epsGrowth3Y": ["EPS Growth", "3 Year"],
  "epsGrowth5Y": ["EPS Growth", "5 Year"],
  "epsGrowthQuarterlyYoy": ["EPS Growth", "Quarterly Year over Year"],
  "epsGrowthTTMYoy": ["EPS Growth", "TTM Year over Year"],
  "epsInclExtraItemsAnnual": ["EPS (includes extra)", "Annual"],
  "epsInclExtraItemsTTM": ["EPS (includes extra)", "TTM"],
  "epsNormalizedAnnual": ["Earnings per Share (EPS)", "Normalized Annual"],
  "focfCagr5Y": ["Free Operating Cash Flow CAGR", "5 Year"],
  "freeCashFlowAnnual": ["Free Cash Flow", "Annual"],
  "freeCashFlowPerShareTTM": ["Free Cash Flow Per Share", "TTM"],
  "freeCashFlowTTM": ["Free Cash Flow", "TTM"],
  "freeOperatingCashFlow/revenue5Y": [
    "Free Operating Cash Flow/Revenue",
    "5 Year"
  ],
  "freeOperatingCashFlow/revenueTTM": [
    "Free Operating Cash Flow/Revenue",
    "TTM"
  ],
  "grossMargin5Y": ["Gross Margin", "5 Year"],
  "grossMarginAnnual": ["Gross Margin", "Annual"],
  "grossMarginTTM": ["Gross Margin", "TTM"],
  "inventoryTurnoverAnnual": ["Inventory Turnover", "Annual"],
  "inventoryTurnoverTTM": ["Inventory Turnover", "TTM"],
  "longTermDebt/equityAnnual": ["Long Term Debt/Equity", "Annual"],
  "longTermDebt/equityQuarterly": ["Long Term Debt/Equity", "Quarterly"],
  "monthToDatePriceReturnDaily": ["Price Return Daily", "Month To Date"],
  "netDebtAnnual": ["Net Debt", "Annual"],
  "netDebtInterim": ["Net Debt", "Annual"],
  "netIncomeEmployeeAnnual": ["Net Income Employee", "Annual"],
  "netIncomeEmployeeTTM": ["Net Income Employee", "TTM"],
  "netInterestCoverageAnnual": ["Net Interest Coverage", "Annual"],
  "netInterestCoverageTTM": ["Net Interest Coverage", "TTM"],
  "netMarginGrowth5Y": ["Net Margin Growth", "5 Year"],
  "netProfitMargin5Y": ["Net Profit Margin", "5 Year"],
  "netProfitMarginAnnual": ["Net Profit Margin", "Annual"],
  "netProfitMarginTTM": ["Net Profit Margin", "TTM"],
  "operatingMargin5Y": ["Operating Margin", "5 Year"],
  "operatingMarginAnnual": ["Operating Margin", "Annual"],
  "operatingMarginTTM": ["Operating Margin", "TTM"],
  "payoutRatioAnnual": ["Payout Ratio", "Annual"],
  "payoutRatioTTM": ["Payout Ratio", "TTM"],
  "pbAnnual": ["Pb", "Annual"],
  "pbQuarterly": ["Pb", "Quarterly"],
  "pcfShareTTM": ["Pcf Share", "TTM"],
  "peBasicExclExtraTTM": ["Pe Basic Excl Extra", "TTM"],
  "peExclExtraAnnual": ["Pe Excl Extra", "Annual"],
  "peExclExtraHighTTM": ["Pe Excl Extra High", "TTM"],
  "peExclExtraTTM": ["Pe Excl Extra", "TTM"],
  "peExclLowTTM": ["Pe Excl Low", "TTM"],
  "peInclExtraTTM": ["Pe Incl Extra", "TTM"],
  "peNormalizedAnnual": ["Pe Normalized", "Annual"],
  "pfcfShareAnnual": ["Pfcf Share", "Annual"],
  "pfcfShareTTM": ["Pfcf Share", "TTM"],
  "pretaxMargin5Y": ["Pretax Margin", "5 Year"],
  "pretaxMarginAnnual": ["Pretax Margin", "Annual"],
  "pretaxMarginTTM": ["Pretax Margin", "TTM"],
  "priceRelativeToS&P500Ytd": ["Price Relative to S&P500", "Year to Date"],
  "priceRelativeToS&P5004Week": ["Price Relative to S&P500", "4 Week"],
  "priceRelativeToS&P50013Week": ["Price Relative to S&P500", "13 Week"],
  "priceRelativeToS&P50026Week": ["Price Relative to S&P500", "26 Week"],
  "priceRelativeToS&P50052Week": ["Price Relative to S&P500", "52 Week"],
  "psAnnual": ["Price to Share Ratio", "Annual"],
  "psTTM": ["Price to Share Ratio", "TTM"],
  "ptbvAnnual": ["Price to Tangible Book Value", "Annual"],
  "ptbvQuarterly": ["Price to Tangible Book Value", "Quarterly"],
  "quickRatioAnnual": ["Quick Ratio", "Annual"],
  "quickRatioQuarterly": ["Quick Ratio", "Quarterly"],
  "receivablesTurnoverAnnual": ["Receivables Turnover", "Annual"],
  "receivablesTurnoverTTM": ["Receivables Turnover", "TTM"],
  "revenueEmployeeAnnual": ["Revenue Employee", "Annual"],
  "revenueEmployeeTTM": ["Revenue Employee", "TTM"],
  "revenueGrowth3Y": ["Revenue Growth", "3 Year"],
  "revenueGrowth5Y": ["Revenue Growth", "5 Year"],
  "revenueGrowthQuarterlyYoy": ["Revenue Growth", "Quarterly"],
  "revenueGrowthTTMYoy": ["Revenue Growth", "TTM"],
  "revenuePerShareAnnual": ["Revenue Per Share", "Annual"],
  "revenuePerShareTTM": ["Revenue Per Share", "TTM"],
  "revenueShareGrowth5Y": ["Revenue Share Growth", "5 Year"],
  "roaRfy": ["Return On Assets", "Fiscal Year"],
  "roaa5Y": ["Return On Average Assets", "5 Year"],
  "roae5Y": ["Return On Average Equity", "5 Year"],
  "roaeTTM": ["Return On Average Equity", "TTM"],
  "roeRfy": ["Return On Equity", "Fiscal Year"],
  "roeTTM": ["Return On Equity", "TTM"],
  "roi5Y": ["Return On Investment", "5 Year"],
  "roiAnnual": ["Return On Investment", "Annual"],
  "roiTTM": ["Return On Investment", "TTM"],
  "tangibleBookValuePerShareAnnual": [
    "Tangible Book Value Per Share",
    "Annual"
  ],
  "tangibleBookValuePerShareQuarterly": [
    "Tangible Book Value Per Share",
    "Quarterly"
  ],
  "tbvCagr5Y": ["Tangible Book Value CAGR", "5 Year"],
  "totalDebt/totalEquityAnnual": ["Total Debt/Total Equity", "Annual"],
  "totalDebt/totalEquityQuarterly": ["Total Debt/Total Equity", "Quarterly"],
  "totalDebtCagr5Y": ["Total Debt CAGR", "5 Year"],
  "yearToDatePriceReturnDaily": ["Price Return Daily", "Year To Date"]
}
